name: meradion
description: Meradio'N live radio listener and RJ studio.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=3.3.0 <4.0.0'}
dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.42
  audio_service: ^0.18.15
  http: ^1.2.2
flutter: {uses-material-design: true}
