from datetime import datetime, timedelta, timezone
SHOWS=[
 {'id':'morning-vibes','title':'Morning Vibes','category':'Music','description':'Warm sounds and bright conversations for your morning.','hosts':['RJ Sai','RJ Rahul'],'artwork':'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80'},
 {'id':'tech-talk','title':'Tech Talk','category':'Technology','description':'Ideas, builders, and the technology shaping tomorrow.','hosts':['RJ Ananya'],'artwork':'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80'},
 {'id':'campus-beats','title':'Campus Beats','category':'Campus','description':'Fresh voices from campus culture.','hosts':['RJ Arjun'],'artwork':'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=900&q=80'},
 {'id':'retro-nights','title':'Retro Nights','category':'Entertainment','description':'Timeless tracks after dark.','hosts':['RJ Sai'],'artwork':'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=900&q=80'},
]
def now_playing(): return {'live':True,'station':'Meradio\'N','stream_url':'','listeners':128,'show':SHOWS[0],'song':{'title':'Golden Hour','artist':'Juniper Lane','artwork':SHOWS[0]['artwork']},'is_demo':True}
def schedule(): return [{'id':'s1','show':SHOWS[0],'starts_at':'10:00 AM','ends_at':'01:00 PM','day':'Today','live':True},{'id':'s2','show':SHOWS[1],'starts_at':'01:00 PM','ends_at':'04:00 PM','day':'Today','live':False},{'id':'s3','show':SHOWS[2],'starts_at':'04:00 PM','ends_at':'06:00 PM','day':'Today','live':False},{'id':'s4','show':SHOWS[3],'starts_at':'08:00 PM','ends_at':'10:00 PM','day':'Tomorrow','live':False}]
def recordings(): return [{'id':'r1','show':SHOWS[0],'title':'Morning Vibes — The Fresh Start','date':'2026-09-28','duration_seconds':3420,'playback_url':'','published':True},{'id':'r2','show':SHOWS[1],'title':'Tech Talk — Human Signals','date':'2026-09-26','duration_seconds':2980,'playback_url':'','published':True},{'id':'r3','show':SHOWS[2],'title':'Campus Beats — Night Shift','date':'2026-09-24','duration_seconds':3675,'playback_url':'','published':True}]
